import { db } from "../lib/firebase";
import { runTransaction, doc, getDoc, setDoc, deleteDoc } from "firebase/firestore";
import { validateTransactionPeriod, validateChequeComponents } from "../services/financialEngine";
import { validateJournalEntry, postAuthoritativeJournalEntry } from "../services/journalEngine";
import { allocateNextSequenceInTransaction } from "../utils/sequenceGenerator";
import { FinancialPeriod, JournalEntryRecord, ChequeComponentItem } from "../types";

// Base helper for printing reports
function printSection(title: string) {
  console.log(`\n==================================================`);
  console.log(title);
  console.log(`==================================================`);
}

async function runUnitTests() {
  printSection("UNIT TESTS");
  let passed = 0;
  let failed = 0;

  const report = (name: string, isPass: boolean, details: string) => {
    if (isPass) {
      passed++;
      console.log(`[PASS] Unit: ${name}\n       Details: ${details}`);
    } else {
      failed++;
      console.error(`[FAIL] Unit: ${name}\n       Details: ${details}`);
    }
  };

  // 1. Financial Period Tests
  const openPeriods: FinancialPeriod[] = [
    {
      id: "p-2026-01",
      name: "Q1 2026",
      startDate: "2026-01-01",
      endDate: "2026-03-31",
      status: "OPEN",
      openedAt: "2026-01-01T00:00:00Z",
      openedBy: "admin"
    }
  ];
  const closedPeriods: FinancialPeriod[] = [
    {
      id: "p-2026-01",
      name: "Q1 2026",
      startDate: "2026-01-01",
      endDate: "2026-03-31",
      status: "CLOSED",
      openedAt: "2026-01-01T00:00:00Z",
      openedBy: "admin"
    }
  ];

  const resOpen = validateTransactionPeriod("2026-02-15", openPeriods);
  report("OPEN financial period allows writes", resOpen.allowed === true, "Allowed correct transaction date.");

  const resClosed = validateTransactionPeriod("2026-02-15", closedPeriods);
  report("CLOSED financial period rejects writes", resClosed.allowed === false, `Blocked date: ${resClosed.errorEn}`);

  const resNull = validateTransactionPeriod("2026-02-15", null as any);
  report("Null financial periods list fails closed", resNull.allowed === false, `Blocked: ${resNull.errorEn}`);

  // 2. Journal Entry Validation Tests
  const balancedEntry = {
    lines: [
      { accountId: "1010", debit: 5000, credit: 0 },
      { accountId: "4010", debit: 0, credit: 5000 }
    ]
  };
  const valBalanced = validateJournalEntry(balancedEntry);
  report("Balanced double-entry journal is valid", valBalanced.isValid === true && valBalanced.totalDebit === 5000, "Debit/Credit equals 5000 AED.");

  const unbalancedEntry = {
    lines: [
      { accountId: "1010", debit: 5000, credit: 0 },
      { accountId: "4010", debit: 0, credit: 4900 }
    ]
  };
  const valUnbalanced = validateJournalEntry(unbalancedEntry);
  report("Unbalanced journal is rejected", valUnbalanced.isValid === false, `Blocked variance: ${valUnbalanced.error}`);

  // 3. Cheque Component Tests
  const components: ChequeComponentItem[] = [
    { id: "c1", type: "RENT", obligationRefId: "obl-1", amount: 3000, descriptionAr: "إيجار", descriptionEn: "Rent" },
    { id: "c2", type: "TENANT_ADMIN_FEE", obligationRefId: "obl-2", amount: 2000, descriptionAr: "رسوم", descriptionEn: "Admin Fee" }
  ];
  const valChequeEqual = validateChequeComponents(5000, components);
  report("Matching cheque component total allowed", valChequeEqual.isValid === true, "Total component sum (3000+2000) equals cheque amount (5000).");

  const valChequeMismatched = validateChequeComponents(4000, components);
  report("Mismatched cheque components rejected", valChequeMismatched.isValid === false, `Blocked difference: ${valChequeMismatched.errorEn}`);

  return { passed, failed };
}

async function runLiveIntegrationTests() {
  printSection("REAL FIRESTORE INTEGRATION TESTS");
  let passed = 0;
  let failed = 0;

  const report = (name: string, isPass: boolean, details: string) => {
    if (isPass) {
      passed++;
      console.log(`[PASS] Live: ${name}\n       Details: ${details}`);
    } else {
      failed++;
      console.error(`[FAIL] Live: ${name}\n       Details: ${details}`);
    }
  };

  const openPeriods: FinancialPeriod[] = [
    {
      id: "p-2026-01",
      name: "Q1 2026",
      startDate: "2026-01-01",
      endDate: "2026-03-31",
      status: "OPEN",
      openedAt: "2026-01-01T00:00:00Z",
      openedBy: "admin"
    }
  ];

  const createSampleJournal = (id: string, sourceType: string, sourceId: string): JournalEntryRecord => ({
    id,
    entryNumber: "", // Autogenerated atomically
    transactionDate: "2026-02-15",
    postingDate: "2026-02-15",
    reference: "REF-123",
    sourceType: sourceType as any,
    sourceId,
    description: "Test Payment Receipt / إيصال استلام تجريبي",
    lines: [
      { id: "jl-1", accountId: "1010", accountCode: "1010", accountNameAr: "الصندوق", accountNameEn: "Cash", debit: 1200, credit: 0 },
      { id: "jl-2", accountId: "4010", accountCode: "4010", accountNameAr: "إيراد إيجار", accountNameEn: "Rent Revenue", debit: 0, credit: 1200 }
    ],
    totalDebit: 1200,
    totalCredit: 1200,
    status: "POSTED",
    createdBy: "Admin",
    createdAt: "2026-02-15T00:00:00Z"
  });

  // ==========================================
  // TEST C: Real Journal Concurrency / Idempotency Test
  // ==========================================
  const concurrentSourceId = "CONC-SRC-" + Date.now();
  const jeIdA = "je-conc-a-" + Date.now();
  const jeIdB = "je-conc-b-" + Date.now();

  const entryA = createSampleJournal(jeIdA, "TEST_CONCURRENT_JOURNAL", concurrentSourceId);
  const entryB = createSampleJournal(jeIdB, "TEST_CONCURRENT_JOURNAL", concurrentSourceId);

  const reqA = runTransaction(db, async (transaction) => {
    return await postAuthoritativeJournalEntry({
      db,
      entry: entryA,
      financialPeriods: openPeriods,
      transaction
    });
  });

  const reqB = runTransaction(db, async (transaction) => {
    return await postAuthoritativeJournalEntry({
      db,
      entry: entryB,
      financialPeriods: openPeriods,
      transaction
    });
  });

  try {
    const results = await Promise.allSettled([reqA, reqB]);
    const successes = results.filter(r => r.status === "fulfilled" && (r.value as any).isValid).length;
    const failures = results.filter(r => r.status === "rejected" || (r.status === "fulfilled" && !(r.value as any).isValid)).length;

    const eventKeyRef = doc(db, "journal_event_keys", `TEST_CONCURRENT_JOURNAL_${concurrentSourceId}`);
    const eventKeySnap = await getDoc(eventKeyRef);

    const docASnap = await getDoc(doc(db, "journal_entries", jeIdA));
    const docBSnap = await getDoc(doc(db, "journal_entries", jeIdB));

    const exactlyOneSuccess = successes === 1 && failures === 1;
    const eventKeyCreated = eventKeySnap.exists();
    const exactlyOneJournalCreated = (docASnap.exists() && !docBSnap.exists()) || (!docASnap.exists() && docBSnap.exists());

    report(
      "Test C: Real Journal Concurrency & Idempotency",
      exactlyOneSuccess && eventKeyCreated && exactlyOneJournalCreated,
      `Successes=${successes}, Failures=${failures}. Event key exists: ${eventKeyCreated}. Exactly one journal saved: ${exactlyOneJournalCreated}.`
    );

    // Clean up
    if (docASnap.exists()) await deleteDoc(doc(db, "journal_entries", jeIdA));
    if (docBSnap.exists()) await deleteDoc(doc(db, "journal_entries", jeIdB));
    if (eventKeySnap.exists()) await deleteDoc(eventKeyRef);

  } catch (err: any) {
    report("Test C: Real Journal Concurrency & Idempotency", false, `Unexpected exception: ${err?.message || err}`);
  }

  // ==========================================
  // TEST E: Real Atomicity & Failure Injection Test
  // ==========================================
  const atomicCaseId = "case-atom-" + Date.now();
  const atomicAllocationId = "pal-atom-" + Date.now();
  const atomicReceiptId = "col-atom-" + Date.now();
  const atomicJournalId = "je-atom-" + Date.now();
  const atomicSourceId = "src-atom-" + Date.now();

  const atomicJournal = createSampleJournal(atomicJournalId, "TEST_ATOMIC_FAILURE", atomicSourceId);

  let transactionThrew = false;
  try {
    await runTransaction(db, async (transaction) => {
      // 1. All Reads / sequence allocations
      const postRes = await postAuthoritativeJournalEntry({
        db,
        entry: atomicJournal,
        financialPeriods: openPeriods,
        transaction
      });
      if (!postRes.isValid) throw new Error(postRes.error);

      // 2. Perform writes
      transaction.set(doc(db, "collections", atomicReceiptId), { amount: 500 });
      transaction.set(doc(db, "payment_allocations", atomicAllocationId), { allocated: 500 });
      transaction.set(doc(db, "cases", atomicCaseId), { caseNumber: "ATOM-1" });

      // 3. FORCE DETERMINISTIC ABORT/FAILURE
      throw new Error("FORCE_DETERMINISTIC_ABORT");
    });
  } catch (err: any) {
    if (err?.message === "FORCE_DETERMINISTIC_ABORT") {
      transactionThrew = true;
    } else {
      console.error("Test E encountered unexpected error:", err);
    }
  }

  // Verify atomic rollback
  const receiptSnap = await getDoc(doc(db, "collections", atomicReceiptId));
  const allocSnap = await getDoc(doc(db, "payment_allocations", atomicAllocationId));
  const caseSnap = await getDoc(doc(db, "cases", atomicCaseId));
  const eventKeySnap = await getDoc(doc(db, "journal_event_keys", `TEST_ATOMIC_FAILURE_${atomicSourceId}`));
  const journalSnap = await getDoc(doc(db, "journal_entries", atomicJournalId));

  const rolledBackSuccessfully = !receiptSnap.exists() &&
                                 !allocSnap.exists() &&
                                 !caseSnap.exists() &&
                                 !eventKeySnap.exists() &&
                                 !journalSnap.exists();

  report(
    "Test E: Real Atomicity & Rollback Integrity on Aborted Transaction",
    transactionThrew && rolledBackSuccessfully,
    `Transaction aborted correctly: ${transactionThrew}. Rolled back all documents: ${rolledBackSuccessfully}.`
  );

  // ==========================================
  // TEST F: Real Reversal Atomicity & Failure Injection Test
  // ==========================================
  const revSourceId = "src-rev-" + Date.now();
  const jeIdOriginal = "je-orig-" + Date.now();
  const jeIdReversal = "je-rev-" + Date.now();

  const origJournal = createSampleJournal(jeIdOriginal, "RENT_COLLECTION", revSourceId);

  // 1. Post original successfully
  await runTransaction(db, async (transaction) => {
    const res = await postAuthoritativeJournalEntry({
      db,
      entry: origJournal,
      financialPeriods: openPeriods,
      transaction
    });
    if (!res.isValid) throw new Error(res.error);
  });

  const origSnapBefore = await getDoc(doc(db, "journal_entries", jeIdOriginal));
  const originalPosted = origSnapBefore.exists() && origSnapBefore.data()?.status === "POSTED";

  // 2. Perform a reversal but force it to abort
  let reversalAborted = false;
  const reversalJournal = createSampleJournal(jeIdReversal, "JOURNAL_REVERSAL", jeIdOriginal);
  reversalJournal.lines = [
    { id: "jl-rev-1", accountId: "1010", accountCode: "1010", accountNameAr: "الصندوق", accountNameEn: "Cash", debit: 0, credit: 1200 },
    { id: "jl-rev-2", accountId: "4010", accountCode: "4010", accountNameAr: "إيراد إيجار", accountNameEn: "Rent Revenue", debit: 1200, credit: 0 }
  ];

  try {
    await runTransaction(db, async (transaction) => {
      const res = await postAuthoritativeJournalEntry({
        db,
        entry: reversalJournal,
        financialPeriods: openPeriods,
        transaction,
        originalJournalToReverse: origSnapBefore.data() as any
      });
      if (!res.isValid) throw new Error(res.error);

      throw new Error("FORCE_REVERSAL_ABORT");
    });
  } catch (err: any) {
    if (err?.message === "FORCE_REVERSAL_ABORT") {
      reversalAborted = true;
    }
  }

  // Verify rollback of reversal
  const origSnapAfterAbort = await getDoc(doc(db, "journal_entries", jeIdOriginal));
  const revSnapAfterAbort = await getDoc(doc(db, "journal_entries", jeIdReversal));
  const rollbackSuccessful = origSnapAfterAbort.data()?.status === "POSTED" && !revSnapAfterAbort.exists();

  // 3. Perform a successful reversal
  await runTransaction(db, async (transaction) => {
    const res = await postAuthoritativeJournalEntry({
      db,
      entry: reversalJournal,
      financialPeriods: openPeriods,
      transaction,
      originalJournalToReverse: origSnapBefore.data() as any
    });
    if (!res.isValid) throw new Error(res.error);
  });

  const origSnapFinal = await getDoc(doc(db, "journal_entries", jeIdOriginal));
  const revSnapFinal = await getDoc(doc(db, "journal_entries", jeIdReversal));

  const originalReversed = origSnapFinal.data()?.status === "REVERSED" && origSnapFinal.data()?.reversalEntryId === jeIdReversal;
  
  // Refined line comparison: compare relevant financial fields
  const getCleanLines = (lines: any[]) => (lines || []).map(l => ({
    accountId: l.accountId,
    debit: l.debit,
    credit: l.credit
  }));
  const originalLinesUnmodified = JSON.stringify(getCleanLines(origSnapFinal.data()?.lines)) === JSON.stringify(getCleanLines(origSnapBefore.data()?.lines));
  const reversalSaved = revSnapFinal.exists() && revSnapFinal.data()?.sourceId === jeIdOriginal;

  report(
    "Test F: Real Reversal Atomicity & Immutability",
    originalPosted && reversalAborted && rollbackSuccessful && originalReversed && originalLinesUnmodified && reversalSaved,
    `Original posted: ${originalPosted}. Reversal abort rollback: ${rollbackSuccessful}. Final state reversed: ${originalReversed}. Lines remain immutable: ${originalLinesUnmodified}.`
  );

  // Clean up
  await deleteDoc(doc(db, "journal_entries", jeIdOriginal));
  await deleteDoc(doc(db, "journal_entries", jeIdReversal));
  await deleteDoc(doc(db, "journal_event_keys", `RENT_COLLECTION_${revSourceId}`));
  await deleteDoc(doc(db, "journal_event_keys", `JOURNAL_REVERSAL_${jeIdOriginal}`));

  // ==========================================
  // TEST G: Sequence Concurrency Test
  // ==========================================
  const seqName = "journal_test_seq_" + Date.now();

  const allocatePromise = (id: number) => {
    return runTransaction(db, async (transaction) => {
      const [seq] = await allocateNextSequenceInTransaction(transaction, db, seqName, "JE-", 1, 5);
      const { flushTransactionWrites } = await import("../utils/sequenceGenerator");
      flushTransactionWrites(transaction);
      return seq;
    });
  };

  try {
    // Start 5 concurrent transactions
    const seqPromises = [
      allocatePromise(1),
      allocatePromise(2),
      allocatePromise(3),
      allocatePromise(4),
      allocatePromise(5)
    ];

    const allocatedSequences = await Promise.all(seqPromises);
    const uniqueSequences = new Set(allocatedSequences);
    const noDuplicates = uniqueSequences.size === 5;

    // Test abort sequence behavior
    let abortTransactionThrew = false;
    try {
      await runTransaction(db, async (transaction) => {
        await allocateNextSequenceInTransaction(transaction, db, seqName, "JE-", 1, 5);
        throw new Error("ABORT_SEQUENCE");
      });
    } catch (err: any) {
      if (err?.message === "ABORT_SEQUENCE") {
        abortTransactionThrew = true;
      }
    }

    // Allocate once more, it should receive the next logical number (6) and not skip (7)
    const finalSeq = await runTransaction(db, async (transaction) => {
      const [seq] = await allocateNextSequenceInTransaction(transaction, db, seqName, "JE-", 1, 5);
      const { flushTransactionWrites } = await import("../utils/sequenceGenerator");
      flushTransactionWrites(transaction);
      return seq;
    });

    const correctSequenceProgression = allocatedSequences.includes("JE-00001") &&
                                       allocatedSequences.includes("JE-00005") &&
                                       finalSeq === "JE-00006";

    report(
      "Test G: Sequence Concurrency and Rollback",
      noDuplicates && abortTransactionThrew && correctSequenceProgression,
      `Allocated sequences: ${allocatedSequences.join(", ")}. Abort handled: ${abortTransactionThrew}. Next sequence after abort: ${finalSeq} (Expected: JE-00006).`
    );

    // Clean up counter
    await deleteDoc(doc(db, "system_counters", seqName));

  } catch (err: any) {
    report("Test G: Sequence Concurrency and Rollback", false, `Unexpected exception: ${err?.message || err}`);
  }

  return { passed, failed };
}

async function main() {
  console.log("=================================================");
  console.log("PHASE 1C-R2.4: SYSTEM FINANCIAL INTEGRITY VERIFIER");
  console.log("=================================================");

  const unitResults = await runUnitTests();
  const liveResults = await runLiveIntegrationTests();

  console.log("\n=================================================");
  console.log("FINAL REPORT SUMMARY");
  console.log("=================================================");
  console.log(`UNIT TESTS:                  ${unitResults.passed} PASSED, ${unitResults.failed} FAILED`);
  console.log(`REAL FIRESTORE INTEGRATION:  ${liveResults.passed} PASSED, ${liveResults.failed} FAILED`);
  console.log("=================================================");

  if (unitResults.failed > 0 || liveResults.failed > 0) {
    console.error("\n[FAIL] SYSTEM FINANCIAL INTEGRITY IS COMPROMISED!");
    process.exit(1);
  } else {
    console.log("\n[SUCCESS] ALL FINANCIAL INTEGRITY CHECKS PASSED!");
    process.exit(0);
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
