const fs = require('fs');
let file = fs.readFileSync('src/components/admin/CentralSystemConfigCenter.tsx', 'utf8');

const regex = /\{smtpTestResult\.safeErrorMessage \|\| "تعذر إتمام مصادقة خادم البريد\."\}\s*<\/div>\s*<\/div>\s*<\/div>\s*<\/div>\s*<div className="space-y-2">/m;

const replacement = `{smtpTestResult.success
                          ? "تم اختبار المصادقة ومقبس SSL بنجاح دون إرسال أي رسالة لمستخدم حقيقي."
                          : smtpTestResult.safeErrorMessage || "تعذر إتمام مصادقة خادم البريد."}
                      </div>
                    </div>
                  </div>
                </div>

                {smtpTestResult.success && (
                  <div className="mt-4 p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
                    <h4 className="text-sm font-bold text-slate-800 dark:text-slate-200 mb-2 flex items-center gap-2">
                      <Send className="w-4 h-4 text-slate-500" />
                      إرسال رسالة بريد اختبارية (Send Test Email)
                    </h4>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">
                      أدخل بريداً إلكترونياً صالحاً لإرسال رسالة اختبارية من النظام للتأكد من وصولها للمستلم.
                    </p>
                    <div className="flex items-center gap-2">
                      <input
                        type="email"
                        id="test-email-recipient"
                        placeholder="test@example.com"
                        className="flex-1 px-3 py-2 text-sm bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg outline-none focus:border-blue-500"
                      />
                      <button
                        onClick={async () => {
                          const input = document.getElementById("test-email-recipient") as HTMLInputElement;
                          if (!input || !input.value) {
                            alert("يرجى إدخال البريد الإلكتروني للمستلم.");
                            return;
                          }
                          const btn = document.getElementById("send-test-btn") as HTMLButtonElement;
                          if (btn) btn.disabled = true;
                          try {
                            const res = await fetch("/api/connections/send-test-email", {
                              method: "POST",
                              headers: { "Content-Type": "application/json", "Authorization": "Bearer " + (localStorage.getItem("token") || "") },
                              body: JSON.stringify({
                                recipientEmail: input.value,
                                subject: "Emirates Falcon ERP — SMTP Test",
                                messageBody: "This is a test email generated by the Emirates Falcon ERP Admin System Configuration Center.\\n\\nResult:\\nSuccessful"
                              }),
                            });
                            const data = await res.json();
                            if (data.success) {
                              alert("✓ تم إرسال رسالة الاختبار بنجاح!");
                              input.value = "";
                            } else {
                              alert("✕ فشل الإرسال: " + data.error);
                            }
                          } catch (err: any) {
                            alert("✕ حدث خطأ: " + err.message);
                          } finally {
                            if (btn) btn.disabled = false;
                          }
                        }}
                        id="send-test-btn"
                        className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-lg disabled:opacity-50"
                      >
                        إرسال (Send)
                      </button>
                    </div>
                  </div>
                )}

                <div className="space-y-2">`;

file = file.replace(regex, replacement);
fs.writeFileSync('src/components/admin/CentralSystemConfigCenter.tsx', file);
console.log("Patched SMTP modal with test email button.");
